server:
  port: 8080
spring:
  mvc:
    #static-path-pattern: /static/**
    static-path-pattern: /**
    view:
      prefix: classpath:/templates/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:com/sue/dao/*Mapper.xml
  type-aliases-package: com.sue.ntity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl